name: build-opencl

on: [push]

jobs:
  windows_opencl:
    name: opencl/release/windows
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v1
    - name: setup
      run: |
       msys2 wget https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/files/1406216/lightOCLSDK.zip -O amdocl.zip
       jar xf amdocl.zip 
       
    - name: build
      run: |
       echo "##[add-path]D:\a\kaktwoos-cl\kaktwoos-cl\lib\x86_64\;D:\a\kaktwoos-cl\kaktwoos-cl\include\"
       gcc -m64 -Ofast -std=c11 .\main.c -o kaktwoos-ocl.exe -LD:\a\kaktwoos-cl\kaktwoos-cl\lib\x86_64\ -ID:\a\kaktwoos-cl\kaktwoos-cl\include\ -lOpenCL -DWANTED_CACTUS_HEIGHT=21
       dir
       
    - uses: actions/upload-artifact@v2
      with:
       name: kaktwoos-ocl-win
       path: .\kaktwoos-ocl.exe


  linux_opencl:
    name: opencl/release/linux
    runs-on: [ubuntu-latest]
    container: nvidia/opencl:devel-ubuntu18.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
       apt-get update && apt-get install -y \
       ocl-icd-opencl-dev gcc && \
       rm -rf /var/lib/apt/lists/*

       gcc -Ofast -std=c11 main.c -o kaktwoos-ocl -lOpenCL -DWANTED_CACTUS_HEIGHT=21
        ls -la
    - uses: actions/upload-artifact@v2
      with:
       name: kaktwoos-ocl-lin
       path: ./kaktwoos-ocl
